// ─── Internal Intelligence Types ─────────────────────────────────────────────

// Month format: YYYY-MM
export type MonthString = string;

// Lens identifiers
export type LensSlug =
  | "faculty-excellence"
  | "student-pipeline"
  | "student-experience"
  | "research-impact"
  | "visibility"
  | "student-outcomes";

// Radar card categories
export type RadarCategory = "attention" | "wins";
export type RadarSeverity = "high" | "medium";
export type MeetingContextTag = "board-ready" | "government" | "donor-ready";

export interface RadarSignalCard {
  id: string;
  category: RadarCategory;
  title: string;
  summary: string;
  sourceLens: LensSlug;
  sourceLensName: string;
  severity?: RadarSeverity;
  isNew?: boolean;
  tags?: MeetingContextTag[];
  date: string;
}

export interface RadarData {
  month: string;
  lastUpdated: string;
  generatedBy: string;
  signalCards: RadarSignalCard[];
}

// Structured What's Next item — separates action text from metadata
export interface WhatsNextItem {
  text: string;
  deadline?: string;
  owner?: string;
}

// Assessment template — every lens follows this
export interface LensAssessment {
  lensSlug: LensSlug;
  month: MonthString;
  headline: string;
  whereWeStand: string[];
  whatsNext: (string | WhatsNextItem)[];
  lastUpdated: string; // ISO date
  narrativeOwner: string;
  isAutoGeneratedOnly: boolean; // true if department owner hasn't enriched yet
}

// Supporting evidence metric
export interface EvidenceMetric {
  id: string;
  label: string;
  value: string | number;
  previousValue?: string | number;
  trend?: "up" | "down" | "stable" | "new";
  trendLabel?: string; // e.g., "+3 from last month"
  format?: "number" | "percentage" | "currency" | "text";
  flagLevel?: "normal" | "amber" | "red"; // for attention items
}

// Lens metadata
export interface LensConfig {
  slug: LensSlug;
  name: string;
  question: string;
  narrativeOwners: string[];
  hasDetailDrilldown: boolean; // e.g., Faculty Excellence has faculty profiles
}

// ─── Faculty Excellence Types ──────────────────────────────────────────────────

// Faculty profile for drilldown
export interface FacultyProfile {
  id: string;
  name: string;
  currentInstitution: string;
  rank: string;
  hiringDivision: string;
  status: "Under negotiation" | "Offer extended" | "Signed";
  statusDate?: string;
  hIndex: number;
  citations: number;
  phdInstitution: string;
  phdAdvisor: string;
  researchFocus: string[];
  topPublications: string[];
  awards: string[];
  academyMemberships: string[];
  fellowships: string[];
  bio: string;
  hiringNotes: string;
}

// Distribution data shapes
export interface DivisionDistribution {
  division: string;
  count: number;
}

export interface NationalityDistribution {
  nationality: string;
  count: number;
}

export interface GenderSplit {
  male: number;
  female: number;
}

// Full Faculty Excellence data shape
export interface FacultyExcellenceData {
  month: string;
  lastUpdated: string;
  narrativeOwner: string;
  isAutoGeneratedOnly: boolean;
  assessment: {
    headline: string;
    whereWeStand: string[];
    whatsNext: (string | WhatsNextItem)[];
  };
  metrics: EvidenceMetric[];
  headcountProgress: { current: number; target: number; label: string };
  distributionByDivision: DivisionDistribution[];
  pipelineQualityComparison: {
    label: string;
    metrics: Array<{
      metric: string;
      currentFacultyValue: number;
      pipelineCandidateValue: number;
      currentFacultyMedian?: number;
      pipelineCandidateMedian?: number;
      format?: "number" | "percentage";
    }>;
  };
  growthByDivision: { division: string; arrivals: number; departures: number; totalFaculty: number }[];
  facultyAchievements: FacultyAchievement[];
  facultyProfiles: FacultyProfile[];
}

export interface FacultyAchievement {
  id: string;
  facultyName: string;
  division: string;
  title: string;
  category:
    | "Award"
    | "Fellowship"
    | "Keynote"
    | "Academy Membership"
    | "Named Position";
  date: string;
  awardingBody: string;
  description: string;
  significance: string;
}

// ─── Student Pipeline Types ─────────────────────────────────────────────────

export interface WeeklyTrend {
  week: string;
  total: number;
}

export interface ProgramDistribution {
  program: string;
  count: number;
}

export interface FeederUniversity {
  university: string;
  count: number;
}

export interface DiversityTarget {
  dimension: string;
  target: number;
  actual: number;
  status: "on-track" | "off-track";
}

export interface HistoricalYearData {
  academicYear: string;
  totalApplications: number;
  top100Applications: number;
  offersIssued: number | null;
  accepted: number | null;
  yieldRate: number | null;
  top100YieldRate: number | null;
}

export interface TrackDistribution {
  track: string;
  count: number;
}

export interface CompetingOfferSummary {
  institution: string;
  outcome: string;
}

export interface StarStudentCompetingOffer {
  institution: string;
  status: string;
}

export interface StarStudent {
  id: string;
  program: "UG" | "Graduate";
  name: string;
  nationality: string;
  track: string;
  status: string;
  previousSchool: string;
  gpa: string;
  achievements: string[];
  competingOffers: StarStudentCompetingOffer[];
  scholarshipStatus: string;
  notes: string;
}

// ─── Student Experience & Outcomes Types ──────────────────────────────────────

export interface StudentAchievement {
  id: string;
  studentName: string;
  program: "UG" | "MSc" | "PhD";
  nationality: string;
  achievementHeadline: string;
  date: string;
  description: string;
  category: "Competition" | "Publication" | "Fellowship" | "Research";
  associatedPublication: string | null;
  associatedAward: string | null;
  facultyAdvisor: string;
  significance: string;
}

export type ProgramDevelopmentScope = "Graduate" | "Undergraduate" | "University-wide";
export type ProgramDevelopmentStatus = "Active" | "In design" | "Completed" | "Under review";

export interface ProgramDevelopment {
  id: string;
  title: string;
  scope: ProgramDevelopmentScope;
  status: ProgramDevelopmentStatus;
  owner: string;
  briefDescription: string;
  fullDescription: string;
  currentProgress: string;
  targetDate: string;
  source: string;
}

export interface HiringOrganization {
  organization: string;
  count: number;
}

export interface EmploymentSector {
  sector: string;
  percentage: number;
}

export interface EmploymentRegion {
  region: string;
  percentage: number;
}

export interface DegreeTypeDistribution {
  type: string;
  count: number;
}

// ─── Student Outcomes Types ──────────────────────────────────────────────────

export interface OutcomesHiringOrg {
  organization: string;
  count: number;
  uaeBased: boolean;
}

export interface OutcomesCohort {
  cohort: string;
  graduates: number;
  employmentRate: number | null;
  uaeRetention: number | null;
  medianTimeMonths: number | null;
  topEmployer: string | null;
  pctAITech: number | null;
  pctResearchSenior: number | null;
  note?: string;
}

export interface OutcomesFilteredMetrics {
  employmentRate: number;
  totalGraduates: number;
  uaeRetention: number;
  pctAITech: number;
}

export interface OutcomesFilteredData {
  metrics: OutcomesFilteredMetrics;
  topEmployers: { organization: string; count: number }[];
}

export interface AlumniHighlight {
  id: string;
  name: string;
  nationality: string;
  graduationYear: number;
  program: string;
  currentRole: string;
  organization: string;
  achievementHeadline: string;
  careerPath: string;
  achievement: string;
  mbzuaiConnection: string;
}

export interface AlumniServiceActivity {
  id: string;
  title: string;
  date: string;
  description: string;
  type: "milestone" | "event" | "program";
}

export interface AlumniServiceAward {
  id: string;
  title: string;
  description: string;
}

// ─── Research Impact Types ────────────────────────────────────────────────────

export interface TierBreakdown {
  tier: string;
  count: number;
}

export interface DivisionPublications {
  division: string;
  tier1: number;
  tier2: number;
  tier3: number;
}

export interface MonthlyPublicationTrend {
  month: string;
  tier1: number;
  tier2: number;
  tier3: number;
}

export interface FlagshipPublication {
  id: string;
  title: string;
  authors: string[];
  venue: string;
  tier: string;
  date: string;
  division: string;
  abstract: string;
  impactFactor: number | null;
  significance: string;
}

export interface Tier1VenueCount {
  venue: string;
  count: number;
}

export interface PatentDistribution {
  category: string;
  count: number;
}

export interface PatentStatusBreakdown {
  status: string;
  count: number;
}

export interface PatentTrendPoint {
  quarter: string;
  filed: number;
  granted: number;
}

export interface FlagshipPatent {
  id: string;
  title: string;
  inventors: string[];
  filingDate: string;
  status: string;
  division: string;
  description: string;
  significance: string;
}

export interface FundingTrendPoint {
  month: string;
  projects: number;
  totalValueM: number;
}

export interface FundingPartner {
  partner: string;
  projects: number;
  totalValueM: number;
}

export interface FlagshipGrant {
  id: string;
  title: string;
  funder: string;
  amount: string;
  pi: string;
  coPIs: string[];
  duration: string;
  startDate: string;
  division: string;
  description: string;
  significance: string;
  status?: string;
}

export interface MOUStatus {
  status: string;
  count: number;
}

export interface PartnerEntry {
  partner: string;
  type: string;
  status: string;
  focus: string;
}

export interface PartnerActivityEntry {
  date: string;
  note: string;
}

export interface EnrichedPartnership {
  id: string;
  name: string;
  type: string;
  status: string;
  focusArea: string;
  lastActivityDate: string;
  keyContactsMBZUAI: string;
  keyContactsPartner: string;
  activityHistory: PartnerActivityEntry[];
  upcoming: string;
  notes: string;
}

export interface UpcomingResearchEvent {
  id: string;
  name: string;
  dateStart: string;
  dateEnd: string;
  type: string;
  location: string;
  description: string;
  speakers: string[];
  chair: string;
  registrationStatus: string;
}

export interface StudentPipelineData {
  month: string;
  lastUpdated: string;
  narrativeOwner: string;
  isAutoGeneratedOnly: boolean;
  graduate: {
    assessment: {
      headline: string;
      whereWeStand: string[];
      whatsNext: string[];
    };
    metrics: EvidenceMetric[];
    weeklyTrend: WeeklyTrend[];
    mscPrograms: ProgramDistribution[];
    phdPrograms: ProgramDistribution[];
    topNationalities: NationalityDistribution[];
    topFeederUniversities: FeederUniversity[];
    historicalComparison: HistoricalYearData[];
    starStudents: StarStudent[];
  };
  undergraduate: {
    assessment: {
      headline: string;
      whereWeStand: string[];
      whatsNext: string[];
    };
    metrics: EvidenceMetric[];
    applicantNationalities: NationalityDistribution[];
    diversityTargets: DiversityTarget[];
    acceptedByTrack: TrackDistribution[];
    starStudents: StarStudent[];
  };
}

// ─── Visibility & Influence ────────────────────────────────────────

export interface MediaHighlight {
  id: string;
  outlet: string;
  type: string;
  title: string;
  date: string | null;
  status: string;
  description: string;
  reach: string;
  significance: string;
  mbzuaiSpokespeople: string[];
  coverageUrl?: string | null;
}

export interface ModelDownloadTrend {
  month: string;
  huggingface?: number;
  k2think: number;
  jais: number;
}

export interface Ranking {
  source: string;
  currentPosition: number | null;
  previousPosition: number | null;
  change: "up" | "down" | "stable" | "new";
  changeLabel: string;
  year: string;
  note: string;
  flagship?: boolean;
}

export type MediaCampaignStatus = "Active" | "In planning" | "Completed";

export interface MediaCampaign {
  id: string;
  name: string;
  status: MediaCampaignStatus;
  briefDescription: string;
  fullDescription: string;
  timeline: string;
  channels: string;
  owner: string;
}

export interface EventDelivered {
  id: string;
  name: string;
  date: string;
  type: string;
  location: string;
  description: string;
  attendees: {
    inPerson: number | null;
    online: number | null;
    total: number | null;
  };
  notableAttendees: string[];
  significance: string;
  mediaGenerated: string | null;
}

export interface HostedDelegation {
  id: string;
  delegation: string;
  date: string;
  size: number;
  purpose: string;
  outcome: string;
  significance: string;
  leadDelegate?: string;
}

export interface UpcomingDelegation {
  id: string;
  delegation: string;
  plannedDate: string;
  size: number;
  purpose: string;
  significance: string;
  leadDelegate?: string;
}

export interface UpcomingEvent {
  id: string;
  name: string;
  date: string;
  type: string;
  expectedAttendees: number;
  keyDelegate: string | null;
}

export interface NotableAttendee {
  id: string;
  name: string;
  title: string;
  program: string;
  significance: string;
}

export interface DelegationRegionalBreakdown {
  region: string;
  count: number;
  mousSigned: number;
}

export interface AlumniEngagementData {
  mentorshipProgram: string;
  alumniSuhoor: string;
  alumniCount: number;
}

export interface AcademyProgram {
  id: string;
  programName: string;
  client: string;
  type: string;
  dates: string;
  participants: number;
  description: string;
  significance: string;
}

export interface OutreachEvent {
  id: string;
  name: string;
  date: string;
  type: string;
  description: string;
  reach: string;
  significance: string;
}

// ─── Media & Brand Assessment Toggle ────────────────────────────────

export type MediaBrandAssessmentView = "marcomms" | "ifm" | "rankings";

export type FlagshipProjectStepStatus = "completed" | "in_progress" | "pending";

export interface FlagshipProjectStep {
  label: string;
  status: FlagshipProjectStepStatus;
  deadline?: string;
}

export interface FlagshipProject {
  id: string;
  title: string;
  objective: string;
  status: string;
  owner?: string;
  finalDeadline: string;
  steps: FlagshipProjectStep[];
}

export interface IFMKpi {
  label: string;
  value: string;
  note?: string;
}

export interface IFMDailyUserPoint {
  date: string;
  users: number;
}

export interface IFMModelDownload {
  model: string;
  downloads: number;
}

export interface IFMExecutiveData {
  executiveSummary: string;
  kpis: IFMKpi[];
  dailyUsersTrend: IFMDailyUserPoint[];
  recentDownloadsByModel: IFMModelDownload[];
}

export interface RankingMovement {
  positions: number;
  direction: "up" | "down" | "flat";
  note?: string;
}

export interface RankingYtdMovement {
  positions: number;
  from: number;
  to: number;
  direction: "up" | "down" | "flat";
}

export interface RankingSummary {
  id: string;
  title: string;
  currentRank: number;
  monthlyMovement: RankingMovement;
  ytdMovement: RankingYtdMovement;
  fields?: string[];
}

// ─── Engagement & Diplomacy Redesign ────────────────────────────────

export type DelegationCategory = "government" | "academic" | "industry";
export type DelegationPriority = "critical" | "high" | "standard";
export type DelegationStatus = "confirmed" | "tentative" | "in_planning";
export type RelationshipTier = "strategic" | "active" | "dormant";

export interface StrategicVisitor {
  name: string;
  title: string;
}

export interface StrategicDelegationPreviousVisit {
  date: string;
  outcome: string;
}

export interface StrategicDelegation {
  id: string;
  institution: string;
  category: DelegationCategory;
  priority: DelegationPriority;
  status: DelegationStatus;
  plannedDate: string;
  size: number;
  purpose: string;
  strategicContext: string;
  keyVisitors: StrategicVisitor[];
  previousVisits: StrategicDelegationPreviousVisit[];
  mouStatus?: string;
  owner: string;
}

export interface InstitutionRelationship {
  id: string;
  institution: string;
  category: DelegationCategory;
  tier: RelationshipTier;
  totalVisits: number;
  lastVisitDate: string;
  lastVisitOutcome: string;
  mouStatus: string;
  keyContactMBZUAI: string;
  keyContactPartner: string;
  oneLiner: string;
}

export interface EngagementFlagshipStep {
  label: string;
  status: "completed" | "in_progress" | "pending";
  deadline?: string;
}

export interface EngagementFlagshipProject {
  id: string;
  title: string;
  objective: string;
  status: string;
  owner: string;
  finalDeadline: string;
  steps: EngagementFlagshipStep[];
}

// ─── The Academy Redesign ──────────────────────────────────────────

export interface AcademyNotableParticipant {
  name: string;
  title: string;
}

export interface AcademyExecutiveProgram {
  id: string;
  title: string;
  client: string;
  cohort: string;
  participants: number;
  dates: string;
  satisfactionRating?: string;
  strategicValue: string;
  keyOutcome: string;
  pipelineNote?: string;
}

export interface AcademyConvening {
  id: string;
  title: string;
  type: string;
  date: string;
  reach: string;
  keyFigure?: string;
  strategicValue: string;
}

export interface AcademyFlagshipDifferentiator {
  id: string;
  title: string;
  tagline: string;
  description: string;
  status: string;
  impact: string;
}

// ─── National Engagement Redesign V2 ──────────────────────────────

export interface PresidentialAttentionIndicator {
  label: string;
  value: string;
}

export interface VisitingMember {
  name: string;
  title: string;
  organization?: string;
}

export interface InternalAttendee {
  name: string;
  title: string;
}

export interface UpcomingDelegation {
  id: string;
  institution: string;
  keyVisitor: string;
  visitorTitle: string;
  visitDate: string;
  strategicPurpose: string;
  mbzuaiLead: string;
  presidentNeeded: boolean | "optional";
  status: string;
  visitingMembers?: VisitingMember[];
  internalAttendees?: InternalAttendee[];
  expectedOutcome?: string;
  previousEngagementDate?: string;
  previousEngagementOutcome?: string;
  nextStep?: string;
}

export interface RecentStrategicVisit {
  id: string;
  institution: string;
  date: string;
  keyVisitor: string;
  mbzuaiHost: string;
  purpose: string;
  outcome: string;
  followUpStatus: string;
}

export interface NEOFlagshipProject {
  id: string;
  title: string;
  significance: string;
  status: string;
  nextMilestone: string;
  strategicValue: string;
  objective?: string;
  recentProgress?: string;
  keyComponents?: string[];
  owner?: string;
}

// ─── The Academy Redesign V2 ──────────────────────────────────────

export interface SeniorLeaderEngaged {
  id: string;
  name: string;
  title: string;
  organization: string;
  program: string;
  period: string;
  whyItMatters: string;
  engagementType?: string;
  strategicSignal?: string;
}

export interface AcademyFlagshipProgram {
  id: string;
  title: string;
  audience: string;
  currentPeriodSignal: string;
  representedEntities: string[];
  strategicValue: string;
  status: string;
  recentProgress?: string;
  whyItMattersToMBZUAI?: string;
  nextMilestone?: string;
}

export interface AcademyConveningV2 {
  id: string;
  title: string;
  date?: string;
  format?: string;
  reached?: string;
  audience?: string;
  notableParticipants?: string[];
  notableExample?: string;
  whyItMatters: string;
  outcome?: string;
  strategicValue?: string;
}

export interface AcademyDifferentiatorV2 {
  id: string;
  title: string;
  significance: string;
  whyItMatters: string;
  currentSignal: string;
  strategicValue: string;
  programShape?: string;
  nextMilestone?: string;
}

// ─── Strategic Accountability ──────────────────────────────────────

export interface DirectiveUpdate {
  date: string;
  note: string;
}

export type DirectiveStatus =
  | "Completed"
  | "In progress"
  | "On track"
  | "Overdue"
  | "Blocked"
  | "Not started";

export type DirectivePriority = "critical" | "high" | "medium";

export type DirectiveSourceType = "Admin SMT" | "A-R SMT" | "Integrated SMT";

export interface Directive {
  id: string;
  title: string;
  description: string;
  source: string;
  sourceType: DirectiveSourceType;
  dateIssued: string;
  owner: string;
  deadline: string | null;
  status: DirectiveStatus;
  statusDate: string;
  priority: DirectivePriority;
  updateHistory: DirectiveUpdate[];
}

// ─── SMT Recap Types ─────────────────────────────────────────────────────────

export type SmtLensTag = LensSlug | "operations";

export interface SmtDecision {
  text: string;
  lensTag: SmtLensTag | null;
}

export interface SmtActionItem {
  action: string;
  owner: string;
  deadline: string | null;
  lensTag?: SmtLensTag | null;
}

export interface SmtMeeting {
  id: string;
  type: "Admin SMT" | "Academic-Research SMT" | "Integrated SMT";
  number: string | null;
  date: string;
  time: string;
  location: string;
  summary: string;
  chair: string;
  attendees: string[];
  apologies: string[];
  keyDecisions: SmtDecision[];
  actionItems: SmtActionItem[];
}

export interface SmtRecapData {
  month: string;
  lastUpdated: string;
  meetings: SmtMeeting[];
}
