"use client";

import { useState } from "react";
import data from "@/lib/data/internal/strategic-accountability.json";
import { getLensConfigOrThrow } from "@/lib/config/lenses";
import { LensPageHeader } from "@/components/internal/shared/LensPageHeader";
import { SectionHeader } from "@/components/internal/shared/SectionHeader";
import { AssessmentBlock } from "@/components/internal/shared/AssessmentBlock";
import { StatusSummaryBar } from "./StatusSummaryBar";
import { DirectiveCardGroup } from "./DirectiveCardGroup";
import { DirectiveModal } from "./DirectiveModal";
import type { Directive, DirectiveStatus } from "@/lib/types/internal-intelligence";

const directives = data.directives as Directive[];

// Group ordering: attention-requiring items first
const STATUS_GROUP_ORDER: DirectiveStatus[] = [
  "Overdue",
  "Blocked",
  "In progress",
  "On track",
  "Not started",
  "Completed",
];

export function StrategicAccountabilityLens() {
  const config = getLensConfigOrThrow("institutional-health");
  const [selected, setSelected] = useState<Directive | null>(null);
  const [modalOpen, setModalOpen] = useState(false);

  function handleCardClick(directive: Directive) {
    setSelected(directive);
    setModalOpen(true);
  }

  // Group directives by status
  const grouped = STATUS_GROUP_ORDER.map((status) => ({
    status,
    directives: directives.filter((d) => d.status === status),
  }));

  return (
    <div className="space-y-10">
      {/* Page Header */}
      <LensPageHeader
        lensName={config.name}
        narrativeOwner={data.narrativeOwner}
        lastUpdated={data.lastUpdated}
        isAutoGeneratedOnly={data.isAutoGeneratedOnly}
      />

      {/* Assessment (shortened: headline + current state + what's ahead) */}
      <div>
        <SectionHeader title="Assessment" />
        <AssessmentBlock assessment={data.assessment} />
      </div>

      {/* Status Summary Bar */}
      <div>
        <SectionHeader title="Execution Status" />
        <StatusSummaryBar directives={directives} />
      </div>

      {/* Directive Cards grouped by status */}
      <div className="space-y-8">
        {grouped.map(({ status, directives: group }) => (
          <DirectiveCardGroup
            key={status}
            status={status}
            directives={group}
            onCardClick={handleCardClick}
          />
        ))}
      </div>

      <DirectiveModal
        directive={selected}
        open={modalOpen}
        onOpenChange={setModalOpen}
      />
    </div>
  );
}
