"use client";

import { useState } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
} from "recharts";
import data from "@/lib/data/internal/student-experience.json";
import { getLensConfigOrThrow } from "@/lib/config/lenses";
import { LensPageHeader } from "@/components/internal/shared/LensPageHeader";
import { SectionHeader } from "@/components/internal/shared/SectionHeader";
import { AssessmentBlock } from "@/components/internal/shared/AssessmentBlock";
import { MetricCard } from "@/components/internal/shared/MetricCard";
import { AchievementCards } from "./AchievementCards";
import { ProgramDevelopmentCards } from "./ProgramDevelopmentCards";
import { ExperienceModeToggle } from "./ExperienceModeToggle";
import type {
  EvidenceMetric,
  StudentAchievement,
  ProgramDevelopment,
  DegreeTypeDistribution,
} from "@/lib/types/internal-intelligence";

const CHART_BLUE = "#3B82F6";
const GRID_COLOR = "var(--border-primary)";
const TICK_COLOR = "var(--text-muted)";
const LABEL_COLOR = "var(--text-secondary)";

// Cast shared data
const allAchievements = data.achievements as StudentAchievement[];
const allDevelopments = data.programDevelopments as ProgramDevelopment[];

// Cast per-side enrollment metrics
const gradMetrics = data.graduate.enrollmentMetrics as EvidenceMetric[];
const ugMetrics = data.undergraduate.enrollmentMetrics as EvidenceMetric[];

// Graduate enrollment breakdown
const gradEnrollmentBreakdown = (data.graduate as Record<string, unknown>).enrollmentBreakdown as DegreeTypeDistribution[];
const gradAchievementDataNote = (data.graduate as Record<string, unknown>).achievementDataNote as string;

// Filter achievements by ID list per side
const gradAchievements = allAchievements.filter((a) =>
  data.graduate.achievementIds.includes(a.id)
);
const ugAchievements = allAchievements.filter((a) =>
  data.undergraduate.achievementIds.includes(a.id)
);

// Filter developments by ID list per side
const gradDevelopments = allDevelopments.filter((d) =>
  data.graduate.programDevelopmentIds.includes(d.id)
);
const ugDevelopments = allDevelopments.filter((d) =>
  data.undergraduate.programDevelopmentIds.includes(d.id)
);

export function StudentExperienceLens() {
  const config = getLensConfigOrThrow("student-experience");
  const [mode, setMode] = useState<"graduate" | "undergraduate">("graduate");

  return (
    <div className="space-y-10">
      {/* Page Header */}
      <LensPageHeader
        lensName={config.name}
        narrativeOwner={data.narrativeOwner}
        lastUpdated={data.lastUpdated}
        isAutoGeneratedOnly={data.isAutoGeneratedOnly}
      />

      {/* Graduate / Undergraduate Toggle */}
      <ExperienceModeToggle mode={mode} onModeChange={setMode} />

      {mode === "graduate" ? (
        <div className="space-y-10">
          {/* Graduate Assessment */}
          <div>
            <SectionHeader title="Assessment" />
            <AssessmentBlock assessment={data.graduate.assessment} />
          </div>

          {/* Graduate Enrollment Metrics — 2-col grid */}
          <div>
            <SectionHeader title="Enrollment" />
            <div className="grid grid-cols-1 md:grid-cols-2 gap-[14px]">
              {gradMetrics.map((metric) => (
                <MetricCard key={metric.id} metric={metric} />
              ))}
            </div>

            {/* PhD vs MSc Breakdown Chart */}
            <div className="mt-4 bg-bg-tertiary rounded-sm border border-border-primary p-4">
              <p className="font-mono text-[11px] uppercase tracking-[0.1em] text-text-muted mb-3">
                Enrollment by Degree Type
              </p>
              <ResponsiveContainer width="100%" height={100}>
                <BarChart
                  data={gradEnrollmentBreakdown}
                  layout="vertical"
                  margin={{ top: 0, right: 30, bottom: 0, left: 0 }}
                >
                  <CartesianGrid stroke={GRID_COLOR} horizontal={false} strokeDasharray="3 3" />
                  <XAxis
                    type="number"
                    tick={{ fill: TICK_COLOR, fontSize: 11, fontFamily: "monospace" }}
                    axisLine={false}
                    tickLine={false}
                  />
                  <YAxis
                    type="category"
                    dataKey="type"
                    tick={{ fill: LABEL_COLOR, fontSize: 11, fontFamily: "monospace" }}
                    width={50}
                    axisLine={false}
                    tickLine={false}
                  />
                  <Bar dataKey="count" fill={CHART_BLUE} radius={[0, 2, 2, 0]} barSize={16} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Graduate Achievements */}
          <div>
            <SectionHeader title="Student Achievements & Highlights" />
            {gradAchievementDataNote && (
              <p className="font-mono text-[14px] text-text-muted italic leading-[1.6] mb-2">
                {gradAchievementDataNote}
              </p>
            )}
            <AchievementCards achievements={gradAchievements} />
          </div>

          {/* Graduate Program Developments */}
          <div>
            <SectionHeader title="Program Developments" />
            <ProgramDevelopmentCards developments={gradDevelopments} />
          </div>
        </div>
      ) : (
        <div className="space-y-10">
          {/* Undergraduate Assessment */}
          <div>
            <SectionHeader title="Assessment" />
            <AssessmentBlock assessment={data.undergraduate.assessment} />
          </div>

          {/* Undergraduate Enrollment Metrics */}
          <div>
            <SectionHeader title="Enrollment" />
            <div className="grid grid-cols-1 md:grid-cols-3 gap-[14px]">
              {ugMetrics.map((metric) => (
                <MetricCard key={metric.id} metric={metric} />
              ))}
            </div>
          </div>

          {/* Undergraduate Achievements */}
          <div>
            <SectionHeader title="Student Achievements & Highlights" />
            <AchievementCards achievements={ugAchievements} />
          </div>

          {/* Undergraduate Program Developments */}
          <div>
            <SectionHeader title="Program Developments" />
            <ProgramDevelopmentCards developments={ugDevelopments} />
          </div>
        </div>
      )}
    </div>
  );
}
