interface LensPageHeaderProps {
  lensName: string;
  narrativeOwner: string;
  lastUpdated: string;
  isAutoGeneratedOnly: boolean;
}

export function LensPageHeader({
  lensName,
  narrativeOwner,
  lastUpdated,
  isAutoGeneratedOnly,
}: LensPageHeaderProps) {
  const formattedDate = new Date(lastUpdated).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const monthDisplay = new Date(lastUpdated).toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
  });

  return (
    <div>
      <h1 className="font-serif text-[28px] text-text-bright">{lensName}</h1>
      <p className="mt-2 font-mono text-[13px] text-text-muted">
        {monthDisplay}
      </p>
      <p className="mt-1 font-mono text-[13px] text-text-muted">
        Narrative owner: {narrativeOwner}
      </p>
      <p className="mt-0.5 font-mono text-[13px] text-text-muted">
        Last updated: {formattedDate}
      </p>

      {isAutoGeneratedOnly && (
        <div className="mt-3 rounded-sm border border-accent-warning/30 bg-accent-warning/5 px-4 py-2.5">
          <p className="font-mono text-[13px] text-accent-warning">
            This assessment has not yet been enriched by the narrative owner.
            Data shown is auto-generated.
          </p>
        </div>
      )}
    </div>
  );
}
