"use client";

import { useState } from "react";
import data from "@/lib/data/internal/research-impact.json";
import { getLensConfigOrThrow } from "@/lib/config/lenses";
import { LensPageHeader } from "@/components/internal/shared/LensPageHeader";
import { SectionHeader } from "@/components/internal/shared/SectionHeader";
import { AssessmentBlock } from "@/components/internal/shared/AssessmentBlock";
import { ResearchModeToggle } from "./ResearchModeToggle";
import type { ResearchTab } from "./ResearchModeToggle";
import { PublicationsSection } from "./PublicationsSection";
import { PatentsSection } from "./PatentsSection";
import { FundingSection } from "./FundingSection";
import { PartnershipsSection } from "./PartnershipsSection";
import { UpcomingResearchEventsSection } from "./UpcomingResearchEventsSection";
import type {
  EvidenceMetric,
  Tier1VenueCount,
  DivisionPublications,
  MonthlyPublicationTrend,
  FlagshipPublication,
  PatentStatusBreakdown,
  PatentTrendPoint,
  FlagshipPatent,
  FundingTrendPoint,
  FundingPartner,
  FlagshipGrant,
  MOUStatus,
  EnrichedPartnership,
  UpcomingResearchEvent,
} from "@/lib/types/internal-intelligence";

// Cast JSON data to typed shapes — Publications
const pubMetrics = data.publications.metrics as EvidenceMetric[];
const tier1ByVenue = (data.publications as Record<string, unknown>).tier1ByVenue as Tier1VenueCount[];
const tier1Definition = (data.publications as Record<string, unknown>).tier1Definition as string;
const byDivision = data.publications.byDivision as DivisionPublications[];
const monthlyTrend = data.publications.monthlyTrend as MonthlyPublicationTrend[];
const flagshipPubs = data.publications.flagshipPublications as FlagshipPublication[];

// Cast — Patents
const patentMetrics = data.patents.metrics as EvidenceMetric[];
const patentStatusBreakdown = (data.patents as Record<string, unknown>).statusBreakdown as PatentStatusBreakdown[];
const studentCoInventorshipNote = (data.patents as Record<string, unknown>).studentCoInventorshipNote as string;
const patentCumulativeTrend = (data.patents as Record<string, unknown>).cumulativeTrend as PatentTrendPoint[];
const flagshipPatents = data.patents.flagshipPatents as FlagshipPatent[];

// Cast — Funding
const fundingMetrics = data.funding.metrics as EvidenceMetric[];
const portfolioTrend = data.funding.portfolioTrend as FundingTrendPoint[];
const keyPartners = data.funding.keyPartners as FundingPartner[];
const flagshipGrants = data.funding.flagshipGrants as FlagshipGrant[];

// Cast — Partnerships
const partnershipMetrics = data.partnerships.metrics as EvidenceMetric[];
const mouStatus = data.partnerships.mouStatus as MOUStatus[];
const enrichedPartners = data.partnerships.enrichedPartners as EnrichedPartnership[];
const partnershipNote = data.partnerships.note as string;

// Cast — Upcoming Research Events
const upcomingEvents = data.upcomingResearchEvents as UpcomingResearchEvent[];

export function ResearchImpactLens() {
  const config = getLensConfigOrThrow("research-impact");
  const [mode, setMode] = useState<ResearchTab>("publications");

  return (
    <div className="space-y-10">
      {/* Page Header */}
      <LensPageHeader
        lensName={config.name}
        narrativeOwner={data.narrativeOwner}
        lastUpdated={data.lastUpdated}
        isAutoGeneratedOnly={data.isAutoGeneratedOnly}
      />

      {/* Assessment */}
      <div>
        <SectionHeader title="Assessment" />
        <AssessmentBlock assessment={data.assessment} />
      </div>

      {/* Supporting Evidence */}
      <div>
        <SectionHeader title="Supporting Evidence" />
        <ResearchModeToggle mode={mode} onModeChange={setMode} />

        {mode === "publications" && (
          <PublicationsSection
            metrics={pubMetrics}
            tier1ByVenue={tier1ByVenue}
            tier1Definition={tier1Definition}
            byDivision={byDivision}
            monthlyTrend={monthlyTrend}
            flagshipPublications={flagshipPubs}
          />
        )}

        {mode === "ip-patents" && (
          <PatentsSection
            metrics={patentMetrics}
            statusBreakdown={patentStatusBreakdown}
            studentCoInventorshipNote={studentCoInventorshipNote}
            cumulativeTrend={patentCumulativeTrend}
            flagshipPatents={flagshipPatents}
          />
        )}

        {mode === "external-funding" && (
          <FundingSection
            metrics={fundingMetrics}
            portfolioTrend={portfolioTrend}
            keyPartners={keyPartners}
            flagshipGrants={flagshipGrants}
          />
        )}

        {mode === "partnership-ecosystem" && (
          <PartnershipsSection
            metrics={partnershipMetrics}
            mouStatus={mouStatus}
            enrichedPartners={enrichedPartners}
            note={partnershipNote}
          />
        )}
      </div>

      {/* Upcoming Research Events — always visible */}
      <div>
        <SectionHeader title="Upcoming Research Events" />
        <UpcomingResearchEventsSection events={upcomingEvents} />
      </div>
    </div>
  );
}
