"use client";

import { useState } from "react";
import data from "@/lib/data/internal/student-pipeline.json";
import { getLensConfigOrThrow } from "@/lib/config/lenses";
import { LensPageHeader } from "@/components/internal/shared/LensPageHeader";
import { SectionHeader } from "@/components/internal/shared/SectionHeader";
import { AssessmentBlock } from "@/components/internal/shared/AssessmentBlock";
import { EvidenceModeToggle } from "./EvidenceModeToggle";
import { GraduateEvidence } from "./GraduateEvidence";
import { UndergraduateEvidence } from "./UndergraduateEvidence";
import type {
  EvidenceMetric,
  ProgramDistribution,
  NationalityDistribution,
  FeederUniversity,
  HistoricalYearData,
  DiversityTarget,
  TrackDistribution,
  StarStudent,
  CompetingOfferSummary,
} from "@/lib/types/internal-intelligence";

// Cast JSON data to typed shapes — Graduate
const gradMetrics = data.graduate.metrics as EvidenceMetric[];
const gradMscPrograms = data.graduate.mscPrograms as ProgramDistribution[];
const gradPhdPrograms = data.graduate.phdPrograms as ProgramDistribution[];
const gradTopNationalities = data.graduate.topNationalities as NationalityDistribution[];
const gradTopFeederUniversities = data.graduate.topFeederUniversities as FeederUniversity[];
const gradAcceptedByProgram = (data.graduate as Record<string, unknown>).acceptedByProgram as ProgramDistribution[];
const gradAcceptedByNationality = (data.graduate as Record<string, unknown>).acceptedByNationality as NationalityDistribution[];
const gradTop100AcceptedByProgram = (data.graduate as Record<string, unknown>).top100AcceptedByProgram as ProgramDistribution[];
const gradHistoricalComparison = data.graduate.historicalComparison as HistoricalYearData[];
const gradStarStudents = data.graduate.starStudents as StarStudent[];

// Cast JSON data to typed shapes — Undergraduate
const ugMetrics = data.undergraduate.metrics as EvidenceMetric[];
const ugAcceptedNationalities = (data.undergraduate as Record<string, unknown>).acceptedNationalities as NationalityDistribution[];
const ugDiversityTargets = data.undergraduate.diversityTargets as DiversityTarget[];
const ugAcceptedByTrack = data.undergraduate.acceptedByTrack as TrackDistribution[];
const ugKeyAwards = (data.undergraduate as Record<string, unknown>).keyAwards as string[];
const ugCompetingOffersSummary = (data.undergraduate as Record<string, unknown>).competingOffersSummary as CompetingOfferSummary[];
const ugStarStudents = data.undergraduate.starStudents as StarStudent[];

export function StudentPipelineLens() {
  const config = getLensConfigOrThrow("student-pipeline");
  const [mode, setMode] = useState<"graduate" | "undergraduate">("graduate");

  return (
    <div className="space-y-10">
      {/* Page Header */}
      <LensPageHeader
        lensName={config.name}
        narrativeOwner={data.narrativeOwner}
        lastUpdated={data.lastUpdated}
        isAutoGeneratedOnly={data.isAutoGeneratedOnly}
      />

      {/* Toggle: Graduate / Undergraduate */}
      <EvidenceModeToggle mode={mode} onModeChange={setMode} />

      {mode === "graduate" ? (
        <div className="space-y-10">
          {/* Graduate Assessment */}
          <div>
            <SectionHeader title="Assessment" />
            <AssessmentBlock assessment={data.graduate.assessment} />
          </div>

          {/* Graduate Supporting Evidence */}
          <div>
            <SectionHeader title="Supporting Evidence" />
            <GraduateEvidence
              metrics={gradMetrics}
              mscPrograms={gradMscPrograms}
              phdPrograms={gradPhdPrograms}
              topNationalities={gradTopNationalities}
              topFeederUniversities={gradTopFeederUniversities}
              acceptedByProgram={gradAcceptedByProgram}
              acceptedByNationality={gradAcceptedByNationality}
              top100AcceptedByProgram={gradTop100AcceptedByProgram}
              historicalComparison={gradHistoricalComparison}
              starStudents={gradStarStudents}
            />
          </div>
        </div>
      ) : (
        <div className="space-y-10">
          {/* Undergraduate Assessment */}
          <div>
            <SectionHeader title="Assessment" />
            <AssessmentBlock assessment={data.undergraduate.assessment} />
          </div>

          {/* Undergraduate Supporting Evidence */}
          <div>
            <SectionHeader title="Supporting Evidence" />
            <UndergraduateEvidence
              metrics={ugMetrics}
              acceptedNationalities={ugAcceptedNationalities}
              diversityTargets={ugDiversityTargets}
              acceptedByTrack={ugAcceptedByTrack}
              keyAwards={ugKeyAwards}
              competingOffersSummary={ugCompetingOffersSummary}
              starStudents={ugStarStudents}
            />
          </div>
        </div>
      )}
    </div>
  );
}
