"use client";

import data from "@/lib/data/internal/faculty-excellence.json";
import { getLensConfigOrThrow } from "@/lib/config/lenses";
import { LensPageHeader } from "@/components/internal/shared/LensPageHeader";
import { SectionHeader } from "@/components/internal/shared/SectionHeader";
import { AssessmentBlock } from "@/components/internal/shared/AssessmentBlock";
import { FacultyMetrics } from "./FacultyMetrics";
import { FacultyCharts } from "./FacultyCharts";
import { FacultyAchievements } from "./FacultyAchievements";
import { FacultyPipelineTable } from "./FacultyPipelineTable";
import type {
  FacultyExcellenceData,
  EvidenceMetric,
  FacultyProfile,
  FacultyAchievement,
} from "@/lib/types/internal-intelligence";

// Cast JSON data to typed shapes
const facultyData = data as FacultyExcellenceData;
const metrics = data.metrics as EvidenceMetric[];
const facultyProfiles = data.facultyProfiles as FacultyProfile[];
const facultyAchievements = data.facultyAchievements as FacultyAchievement[];
const pipelineQualityComparison = facultyData.pipelineQualityComparison as FacultyExcellenceData["pipelineQualityComparison"];
const growthByDivision = data.growthByDivision;

export function FacultyExcellenceLens() {
  const config = getLensConfigOrThrow("faculty-excellence");

  return (
    <div className="space-y-10">
      {/* Page Header */}
      <LensPageHeader
        lensName={config.name}
        narrativeOwner={data.narrativeOwner}
        lastUpdated={data.lastUpdated}
        isAutoGeneratedOnly={data.isAutoGeneratedOnly}
      />

      {/* Assessment */}
      <div>
        <SectionHeader title="Assessment" />
        <AssessmentBlock assessment={data.assessment} />
      </div>

      {/* Supporting Evidence */}
      <div>
        <SectionHeader title="Supporting Evidence" />
        <FacultyMetrics metrics={metrics} />
        <FacultyCharts
          pipelineQualityComparison={pipelineQualityComparison}
          growthByDivision={growthByDivision}
        />
      </div>

      {/* Faculty Achievements & Recognition */}
      <div>
        <SectionHeader title="Faculty Achievements & Recognition" />
        <FacultyAchievements achievements={facultyAchievements} />
      </div>

      {/* Faculty Pipeline & Recent Hires */}
      <div>
        <SectionHeader title="Faculty Pipeline & Recent Hires" />
        <FacultyPipelineTable profiles={facultyProfiles} />
      </div>
    </div>
  );
}
