"use client";

import { useState } from "react";
import data from "@/lib/data/internal/visibility.json";
import { getLensConfigOrThrow } from "@/lib/config/lenses";
import { LensPageHeader } from "@/components/internal/shared/LensPageHeader";
import { SectionHeader } from "@/components/internal/shared/SectionHeader";
import { AssessmentBlock } from "@/components/internal/shared/AssessmentBlock";
import { VisibilityTabs } from "./VisibilityTabs";
import type { VisibilityMode } from "./VisibilityTabs";
import { AssessmentViewToggle } from "./AssessmentViewToggle";
import { FlagshipProjectCards } from "./FlagshipProjectCards";
import { IFMExecutiveView } from "./IFMExecutiveView";
import { RankingsSummaryCards } from "./RankingsSummaryCards";
import { MediaHighlightCards } from "./MediaHighlightCards";
import { PresidentialAttentionStrip } from "./PresidentialAttentionStrip";
import { UpcomingDelegationCards } from "./UpcomingDelegationCards";
import { RecentStrategicVisits } from "./RecentStrategicVisits";
import { NEOFlagshipCards } from "./NEOFlagshipCards";
import { SeniorLeaderCards } from "./SeniorLeaderCards";
import { AcademyFlagshipProgramCards } from "./AcademyFlagshipProgramCards";
import { AcademyConveningsCards } from "./AcademyConveningsCards";
import { AcademyDifferentiatorCards } from "./AcademyDifferentiatorCards";
import { InstitutionalReachStrip } from "./InstitutionalReachStrip";
import type {
  MediaHighlight,
  MediaBrandAssessmentView,
  FlagshipProject,
  IFMExecutiveData,
  RankingSummary,
  PresidentialAttentionIndicator,
  UpcomingDelegation,
  RecentStrategicVisit,
  NEOFlagshipProject,
  SeniorLeaderEngaged,
  AcademyFlagshipProgram,
  AcademyConveningV2,
  AcademyDifferentiatorV2,
  IFMKpi,
} from "@/lib/types/internal-intelligence";

// Per-mode assessments
const mediaBrandAssessment = data.mediaBrand.assessment;

// Cast JSON data — Media & Brand
const mediaHighlights = data.mediaBrand.mediaHighlights as MediaHighlight[];
const flagshipProjects = (data.mediaBrand as Record<string, unknown>).flagshipProjects as FlagshipProject[];
const ifmExecutive = (data.mediaBrand as Record<string, unknown>).ifmExecutive as IFMExecutiveData;
const rankingsSummary = (data.mediaBrand as Record<string, unknown>).rankingsSummary as RankingSummary[];

// Cast — National Engagement & Outreach
const engagementAssessmentSummary = (data.engagementDiplomacy as Record<string, unknown>).assessmentSummary as string;
const presidentialAttention = (data.engagementDiplomacy as Record<string, unknown>).presidentialAttentionThisMonth as PresidentialAttentionIndicator[];
const upcomingDelegations = (data.engagementDiplomacy as Record<string, unknown>).upcomingHighPriorityDelegations as UpcomingDelegation[];
const recentStrategicVisits = (data.engagementDiplomacy as Record<string, unknown>).recentStrategicVisits as RecentStrategicVisit[];
const neoFlagshipProjects = (data.engagementDiplomacy as Record<string, unknown>).flagshipProjects as NEOFlagshipProject[];

// Cast — The Academy
const academyAssessmentSummary = (data.outreachEducation as Record<string, unknown>).assessmentSummary as string;
const seniorLeaders = (data.outreachEducation as Record<string, unknown>).seniorLeadersEngaged as SeniorLeaderEngaged[];
const academyFlagshipPrograms = (data.outreachEducation as Record<string, unknown>).flagshipExecutivePrograms as AcademyFlagshipProgram[];
const academyConvenings = (data.outreachEducation as Record<string, unknown>).convenings as AcademyConveningV2[];
const academyDifferentiators = (data.outreachEducation as Record<string, unknown>).flagshipDifferentiators as AcademyDifferentiatorV2[];
const institutionalReach = (data.outreachEducation as Record<string, unknown>).institutionalReachToDate as IFMKpi[];

export function VisibilityLens() {
  const config = getLensConfigOrThrow("visibility");
  const [mode, setMode] = useState<VisibilityMode>("media");
  const [assessmentView, setAssessmentView] = useState<MediaBrandAssessmentView>("marcomms");

  return (
    <div className="space-y-10">
      {/* Page Header */}
      <LensPageHeader
        lensName={config.name}
        narrativeOwner={data.narrativeOwner}
        lastUpdated={data.lastUpdated}
        isAutoGeneratedOnly={data.isAutoGeneratedOnly}
      />

      {/* Tab Toggle */}
      <VisibilityTabs mode={mode} onModeChange={setMode} />

      {/* ── Media & Brand ──────────────────────────────────────────────── */}
      {mode === "media" && (
        <div className="space-y-10">
          {/* Assessment — always visible */}
          <div>
            <SectionHeader title="Assessment" />
            <AssessmentBlock assessment={mediaBrandAssessment} />
          </div>

          {/* Executive Views toggle */}
          <div>
            <AssessmentViewToggle view={assessmentView} onViewChange={setAssessmentView} />

            {/* MarComms View (default) */}
            {assessmentView === "marcomms" && (
              <div className="space-y-8">
                <div>
                  <p className="font-mono text-[11px] uppercase tracking-[0.1em] text-text-muted mb-4">
                    Flagship Projects
                  </p>
                  <FlagshipProjectCards projects={flagshipProjects} />
                </div>

                <MediaHighlightCards highlights={mediaHighlights} />
              </div>
            )}

            {/* IFM View */}
            {assessmentView === "ifm" && (
              <IFMExecutiveView data={ifmExecutive} />
            )}

            {/* Rankings View */}
            {assessmentView === "rankings" && (
              <RankingsSummaryCards summaries={rankingsSummary} />
            )}
          </div>

        </div>
      )}

      {/* ── National Engagement & Outreach ──────────────────────────────── */}
      {mode === "engagement" && (
        <div className="space-y-10">
          {/* Assessment — single paragraph */}
          <div>
            <SectionHeader title="Assessment" />
            <p className="font-serif text-base font-medium leading-[1.6] text-sig-high">
              {engagementAssessmentSummary}
            </p>
          </div>

          {/* Presidential Attention This Month */}
          <div>
            <SectionHeader title="Presidential Attention This Month" />
            <PresidentialAttentionStrip indicators={presidentialAttention} />
          </div>

          {/* Upcoming High-Priority Delegations */}
          <div>
            <SectionHeader title="Upcoming High-Priority Delegations" />
            <UpcomingDelegationCards delegations={upcomingDelegations} />
          </div>

          {/* Recent Strategic Visits */}
          <div>
            <SectionHeader title="Recent Strategic Visits" />
            <RecentStrategicVisits visits={recentStrategicVisits} />
          </div>

          {/* Flagship Projects */}
          <div>
            <SectionHeader title="Flagship Projects" />
            <NEOFlagshipCards projects={neoFlagshipProjects} />
          </div>
        </div>
      )}

      {/* ── The Academy ────────────────────────────────────────────────── */}
      {mode === "outreach" && (
        <div className="space-y-10">
          {/* Assessment — single paragraph */}
          <div>
            <SectionHeader title="Assessment" />
            <p className="font-serif text-base font-medium leading-[1.6] text-sig-high">
              {academyAssessmentSummary}
            </p>
          </div>

          {/* Senior Leaders Engaged This Period */}
          <div>
            <SectionHeader title="Senior Leaders Engaged This Period" />
            <SeniorLeaderCards leaders={seniorLeaders} />
          </div>

          {/* Flagship Executive Programs */}
          <div>
            <SectionHeader title="Flagship Executive Programs" />
            <AcademyFlagshipProgramCards programs={academyFlagshipPrograms} />
          </div>

          {/* Influence & Convenings */}
          <div>
            <SectionHeader title="Influence & Convenings" />
            <AcademyConveningsCards convenings={academyConvenings} />
          </div>

          {/* Flagship Differentiators */}
          <div>
            <SectionHeader title="Flagship Differentiators" />
            <AcademyDifferentiatorCards differentiators={academyDifferentiators} />
          </div>

          {/* Institutional Reach to Date */}
          <div>
            <SectionHeader title="Institutional Reach to Date" />
            <InstitutionalReachStrip metrics={institutionalReach} />
          </div>
        </div>
      )}
    </div>
  );
}
